# Generated by Django 3.2.12 on 2022-03-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tododata',
            name='date',
            field=models.DateField(default='1999-01-01'),
            preserve_default=False,
        ),
    ]
