# Generated by Django 3.2.12 on 2022-03-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_tododata_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododata',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
